name: Build & Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build site
        run: |
          python build.py
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # Der Ort, aus dem deployiert wird:
          # docs ist generierter Output
          # Der deploy-pages action nimmt artifacts, also zip docs, upload und deploy
          # Standardmäßig ist Artefaktname "github-pages"
